version: "1.0"
stages:
  - "clone"
  - "build"
  - "deploy"
  - "qa"
steps:
  clone:
    stage: "clone"
    title: "Cloning CFOS"
    type: "git-clone"
    repo: "metacell/cfos-visualizer"
    revision: "${{CF_BRANCH}}"
  build:
    stage: "build"
    title: "Building CFOS"
    type: "build"
    image_name: "cfos"
    tag: "${{CF_SHORT_REVISION}}"
    dockerfile: Dockerfile
    working_directory: ./cfos-visualizer
    buildkit: true    
    registry: "${{CODEFRESH_REGISTRY}}"
  deploy:
    stage: "deploy"
    title: "Deploying CFOS VIZ"
    image: codefresh/cf-deploy-kubernetes
    tag: latest
    working_directory: ./cfos-visualizer/deploy/k8s
    commands:
      - /cf-deploy-kubernetes cfos.yaml
      - /cf-deploy-kubernetes ingress.yaml
    environment:
      - KUBECONTEXT=${{CLUSTER_NAME}}
      - KUBERNETES_NAMESPACE=${{NAMESPACE}}
  test_image:
    title: "Building Integration Image"
    type: "build"
    stage: "qa"
    image_name: "cfos-e2e"
    tag: '${{CF_SHORT_REVISION}}'
    working_directory: ./cfos-visualizer/tests/e2e
    disable_push: True
  e2e_tests:
    title: "End to End tests"
    stage: "qa"
    image: '${{test_image}}'
    fail_fast: false
    environment:
      - url=https://${{DOMAIN}}
    commands:
      - bash -c "rm -rf /codefresh/volume/cfos-visualizer/tests"
      - echo $url
      - bash -c "cd / && npm test"      