export const actions = {
    // Viewer action types
    SET_VIEWER_ATLAS: 'SET_VIEWER_ATLAS',
    FETCH_AND_ADD_ACTIVITY_MAP_TO_VIEWER: 'FETCH_AND_ADD_ACTIVITY_MAP_TO_VIEWER',
    ADD_ACTIVITY_MAP_TO_VIEWER: 'ADD_ACTIVITY_MAP_TO_VIEWER',
    REMOVE_ACTIVITY_MAP_FROM_VIEWER: 'REMOVE_ACTIVITY_MAP_FROM_VIEWER',
    TOGGLE_VIEWER_OBJECT_VISIBILITY: 'TOGGLE_VIEWER_OBJECT_VISIBILITY',
    CHANGE_VIEWER_OBJECT_OPACITY: 'CHANGE_VIEWER_OBJECT_OPACITY',
    CHANGE_ALL_VIEWER_OBJECTS_OPACITY: 'CHANGE_ALL_ACTIVITY_MAPS_OPACITY',
    CHANGE_ACTIVITY_MAP_LUT: 'CHANGE_ACTIVITY_MAP_LUT',
    CHANGE_VIEWER_ORDER: 'CHANGE_VIEWER_ORDER',
    DOWNLOAD_VIEWER_OBJECT: 'DOWNLOAD_VIEWER_OBJECT',
    DOWNLOAD_ALL_OBJECTS: 'DOWNLOAD_ALL_OBJECTS',

    // Experiment action types
    FETCH_AND_SET_CURRENT_EXPERIMENT_AND_ATLAS: 'FETCH_AND_SET_CURRENT_EXPERIMENT_AND_ATLAS',
    SET_CURRENT_EXPERIMENT: 'SET_CURRENT_EXPERIMENT',
    FETCH_MODEL: 'FETCH_MODEL_DATA',
    SET_MODEL: 'SET_MODEL_DATA',

    // UI action types
    SET_LOADING: 'SET_LOADING',
    SET_ERROR: 'SET_ERROR'
};

