export const actions = {
    // Viewer action types
    ADD_OBJECT_TO_VIEWER: 'ADD_OBJECT_TO_VIEWER',
    REMOVE_OBJECT_FROM_VIEWER: 'REMOVE_OBJECT_FROM_VIEWER',
    TOGGLE_OBJECT_VISIBILITY: 'TOGGLE_OBJECT_VISIBILITY',
    CHANGE_OBJECT_OPACITY: 'CHANGE_OBJECT_OPACITY',
    CHANGE_ALL_OBJECTS_OPACITY: 'CHANGE_ALL_OBJECTS_OPACITY',

    // Experiment action types
    SET_CURRENT_EXPERIMENT: 'SET_CURRENT_EXPERIMENT',
    FETCH_MODEL_DATA: 'FETCH_MODEL_DATA',
    FETCH_MODEL_DATA_SUCCESS: 'FETCH_MODEL_DATA_SUCCESS',
    FETCH_MODEL_DATA_FAILURE: 'FETCH_MODEL_DATA_FAILURE',

    // UI action types
    SET_LOADING: 'SET_LOADING',
    SET_ERROR: 'SET_ERROR'
};

