export const actions = {
    // Viewer action types
    FETCH_AND_ADD_ACTIVITY_MAP_TO_VIEWER: 'FETCH_AND_ADD_ACTIVITY_MAP_TO_VIEWER',
    ADD_ACTIVITY_MAP_TO_VIEWER: 'ADD_ACTIVITY_MAP_TO_VIEWER',
    REMOVE_ACTIVITY_MAP_FROM_VIEWER: 'REMOVE_ACTIVITY_MAP_FROM_VIEWER',
    TOGGLE_ACTIVITY_MAP_VISIBILITY: 'TOGGLE_ACTIVITY_MAP_VISIBILITY',
    CHANGE_ACTIVITY_MAP_OPACITY: 'CHANGE_ACTIVITY_MAP_OPACITY',
    CHANGE_ALL_ACTIVITY_MAPS_OPACITY: 'CHANGE_ALL_ACTIVITY_MAPS_OPACITY',
    CHANGE_ACTIVITY_MAP_COLOR: 'CHANGE_ACTIVITY_MAP_COLOR',
    CHANGE_ACTIVITY_MAPS_ORDER: 'CHANGE_ACTIVITY_MAPS_ORDER',
    DOWNLOAD_ACTIVITY_MAP: 'DOWNLOAD_ACTIVITY_MAP',
    DOWNLOAD_ALL_OBJECTS: 'DOWNLOAD_ALL_OBJECTS',

    // Experiment action types
    FETCH_CURRENT_EXPERIMENT: 'FETCH_CURRENT_EXPERIMENT',
    SET_CURRENT_EXPERIMENT: 'SET_CURRENT_EXPERIMENT',
    FETCH_MODEL: 'FETCH_MODEL_DATA',
    SET_MODEL: 'SET_MODEL_DATA',

    // UI action types
    SET_LOADING: 'SET_LOADING',
    SET_ERROR: 'SET_ERROR'
};

