apiVersion: apps/v1
kind: Deployment
metadata:
  name: cfos-visualizer
spec:
  selector:
    matchLabels:
      app: cfos-visualizer
  replicas: 1
  template:
    metadata:
      labels:
        app: cfos-visualizer
    spec:
      containers:
        - name: cfos-visualizer
          image: "{{REGISTRY}}cfos-visualizer:{{TAG}}"
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "25m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: cfos-visualizer
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: cfos-visualizer
