export const actions = {
    // Viewer action types
    SET_VIEWER_ATLAS: 'SET_VIEWER_ATLAS',
    FETCH_AND_ADD_ACTIVITY_MAP_TO_VIEWER: 'FETCH_AND_ADD_ACTIVITY_MAP_TO_VIEWER',
    ADD_ACTIVITY_MAP_TO_VIEWER: 'ADD_ACTIVITY_MAP_TO_VIEWER',
    REMOVE_ACTIVITY_MAP_FROM_VIEWER: 'REMOVE_ACTIVITY_MAP_FROM_VIEWER',
    TOGGLE_VIEWER_OBJECT_VISIBILITY: 'TOGGLE_VIEWER_OBJECT_VISIBILITY',
    CHANGE_ACTIVITY_MAP_INTENSITY_RANGE: 'CHANGE_ACTIVITY_MAP_INTENSITY_RANGE',
    CHANGE_ALL_ACTIVITY_MAP_INTENSITY_RANGE: 'CHANGE_ALL_ACTIVITY_MAP_INTENSITY_RANGE',
    CHANGE_ACTIVITY_MAP_COLOR_RANGE: 'CHANGE_ACTIVITY_MAP_COLOR_RANGE',
    CHANGE_VIEWER_ORDER: 'CHANGE_VIEWER_ORDER',
    DOWNLOAD_VIEWER_OBJECT: 'DOWNLOAD_VIEWER_OBJECT',
    DOWNLOAD_ALL_OBJECTS: 'DOWNLOAD_ALL_OBJECTS',

    // Experiment action types
    FETCH_AND_SET_CURRENT_EXPERIMENT_AND_ATLAS: 'FETCH_AND_SET_CURRENT_EXPERIMENT_AND_ATLAS',
    SET_CURRENT_EXPERIMENT: 'SET_CURRENT_EXPERIMENT',
    FETCH_MODEL: 'FETCH_MODEL_DATA',
    SET_MODEL: 'SET_MODEL_DATA',

    // UI action types
    START_LOADING: 'START_LOADING',
    STOP_LOADING: 'STOP_LOADING',
    SET_ERROR: 'SET_ERROR'
};

export const messages = {
    NO_METADATA: "No metadata available",
    NO_DESCRIPTION: "No description available"
}

export const sceneObjects = {
    CAMERA: 'camera',
    ATLAS: 'atlas',
    ATLAS_WIREFRAME: 'atlas_wireframe',
    ACTIVITY_MAP: 'activity_map'
}