# Default values for cfos-visualizer.
# This is a YAML-formatted file.

replicaCount: 1

image:
  repository: ""  # Will be overridden by pipeline
  pullPolicy: IfNotPresent
  tag: ""  # Will be overridden by pipeline

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: ""  # Will be overridden by pipeline
      paths:
        - path: /
          pathType: ImplementationSpecific
